### ISSUE TITLE
test and train images and labels files missing

### ISSUE THREAD

**Issue by myusrn** [ryanchynoweth44/AzureMachineLearningWithDatabricks#2]
The master/AzureMLWithAzureDatabricks/walkthrough/01_SetUpAzureEnvironment.md Get Data section has 4 links to test and train images and labels files that produce an "rserverdata.blob.core.windows.net’s server IP address could not be found." error.

Can these be restored so the walk through can be completed or is it no longer being supported?

Theses are the actual links
1. https://bit.ly/2VaO7cj -> https://rserverdata.blob.core.windows.net/public/test-images.gz
2. https://bit.ly/2Ve9Yzx -> https://rserverdata.blob.core.windows.net/public/test-labels.gz
3. https://bit.ly/2GDXqhK -> https://rserverdata.blob.core.windows.net/public/train-images.gz
4. https://bit.ly/2V7McW9 -> https://rserverdata.blob.core.windows.net/public/train-labels.gz

**Comment by ryanchynoweth44** [comment]
Yes we will get this fixed. We will likely convert this to use the sklearn datasets API but that is TBD.

**Comment by ryanchynoweth44** [comment]
Updated the data files link to reference the [mnist page](http://yann.lecun.com/exdb/mnist/).
