### ISSUE TITLE
determining workspace name to use in workspace connection api call

### ISSUE THREAD

**Issue by myusrn** [ryanchynoweth44/AzureMachineLearningWithDatabricks#3]
When i get to the part involving the following notebook code . . . 

```
ws = Workspace(subscription_id = subscription_id, resource_group = resource_group, workspace_name = workspace_name)
```

. . . i'm hitting issue where it doesn't seem to like the workspace_name values i've tried.  I tried using the `workspace_name = "<azure dashboard databricks service name>`  and it produces `"error": { "message": "Workspace not found." }`.   

Any additional guidance on how one determines what that workspace_name argument value needs to be for things to work?

Fyi, on a related front when i first ran the above databricks workspace connection command i was getting the errors listed below that appear to arise when your aad msa [ microsoft account ] / aka psa [ personal account ] or wsa [ work or school account ] has been granted access to more than one azure subscription.  The work around provided in error output referenced `aka.ms/aml-notebook-auth` documetation was to switch to including InteractiveLoginAuthentication argument that defines the aad tenant id associated with the azure subscription you are trying to authenticate to.  Might be worth adding a note to instructions about this if you expect folks to typically have an aad signin that is enabled with access to multiple azure subscriptions paired with different aad tenants.

```
from azureml.core.authentication import InteractiveLoginAuthentication
interactive_auth = InteractiveLoginAuthentication(tenant_id = tenant_id)
ws = Workspace(subscription_id = subscription_id, resource_group = resource_group, workspace_name = workspace_name, auth = interactive_auth)
```

```
ws = Workspace(subscription_id = subscription_id, resource_group = resource_group, workspace_name = workspace_name)
---------------------------------------------------------------------------------------------
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E4XTNBVH8 to authenticate.
Interactive authentication successfully completed.
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code EYKVEU4QY to authenticate.
Interactive authentication successfully completed.
UserErrorException: UserErrorException:
---------------------------------------------------------------------------------------------
UserErrorException: UserErrorException:
	Message: You are currently logged-in to <guid of aad tenant that is paired with azure subscription i don't want access to> tenant. You don't have access to <guid of azure subscription i do want access to> subscription, please check if it is in this tenant. All the subscriptions that you have access to in this tenant are = 
 [SubscriptionInfo(subscription_name='<name of azure subscription i don't want access to>', subscription_id='<guid of azure subscription i don't want access to>')]. 
 Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "You are currently logged-in to <guid of aad tenant that is paired with azure subscription i don't want access to> tenant. You don't have access to <guid of azure subscription i do want access to> subscription, please check if it is in this tenant. All the subscriptions that you have access to in this tenant are = \n [SubscriptionInfo(subscription_name='<name of azure subscription i don't want access to>', subscription_id='<guid of azure subscription i don't want access to>')]. \n Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.",
        "code": "UserError"
    }
}
```

**Comment by ryanchynoweth44** [comment]
Sorry it took me a while to respond. I never received an alert on this issue via email from github. 

It looks like you are using the interactive login to authenticate against the Azure Machine Learning Workspace. When you run the workspace command are you being redirected to a Microsoft login screen in your browser?
The workspace name is simply the name of your workspace that is found in step 6 in the link [here](https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-1st-experiment-sdk-setup#create-a-workspace). 

The best/correct alternative would be to authenticate with a service principle, which I can provide information on how to do so. This is how users should do when moving code into production anyways.

**Comment by myusrn** [comment]
Yes i was being provided https://microsoft.com/devicelogin url to open in browser to carry out signin with.  It was failing because my signin had access to multiple azure subscriptions.  The code i showed above is what i found in docs that allowed me to successfully have the workspace connection established against my azure subscription where the databricks workspace was defined.  

This issue is really only meant as an fyi in the event that you want to update your walk through to discuss handling the case where users have signin that has access to > 1 azure subscription and perhaps clarify where workspace_name value comes from for those who are not able to determine what that is so readily.

**Comment by ryanchynoweth44** [comment]
Okay I understand know. Thank you. I am going to close this out. We will update or refrence your code if other users run into similar issues. Thanks!
